<<<<<<< HEAD
# Generated by Django 5.2.8 on 2025-11-28 13:35

import datetime
=======
# Generated by Django 5.2.8 on 2025-11-28 17:03

import datetime
import django.db.models.deletion
>>>>>>> sebastian
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('usuario', models.CharField(max_length=50, unique=True, verbose_name='Usuario')),
                ('contrasena', models.CharField(max_length=255, verbose_name='Contraseña')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('fechaRegistro', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'administrador',
                'verbose_name_plural': 'administradores',
                'db_table': 'administrador',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('fechaCasastro', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMarca', models.CharField(max_length=100, verbose_name='Nombre Marca')),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marcas',
                'db_table': 'marca',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('envio', models.IntegerField(default=1, verbose_name='Envío')),
                ('fechaRegistro', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
                'db_table': 'proveedor',
            },
        ),
<<<<<<< HEAD
=======
        migrations.CreateModel(
            name='TipoProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=100, verbose_name='Nombre Tipo Producto')),
                ('descripcion', models.TextField(verbose_name='Descripción Tipo Producto')),
            ],
            options={
                'verbose_name': 'Tipo Producto',
                'verbose_name_plural': 'Tipos de Productos',
                'db_table': 'tipo_productos',
            },
        ),
        migrations.CreateModel(
            name='unidad_medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_unidad', models.CharField(max_length=100, verbose_name='Nombre Unidad de Medida')),
                ('abreviatura', models.CharField(max_length=10, verbose_name='Abreviatura')),
            ],
            options={
                'verbose_name': 'unidad de medida',
                'verbose_name_plural': 'unidades de medida',
                'db_table': 'unidad_medida',
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField()),
                ('estado_pedido', models.CharField(max_length=150)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.administrador')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedidos',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('idMarca', models.ForeignKey(db_column='idMarca', on_delete=django.db.models.deletion.CASCADE, to='app.marca')),
                ('idTipo', models.ForeignKey(db_column='idTipo', on_delete=django.db.models.deletion.CASCADE, to='app.tipoproductos')),
                ('idUnidad', models.ForeignKey(db_column='idUnidad', on_delete=django.db.models.deletion.CASCADE, to='app.unidad_medida')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField(default=datetime.datetime.now)),
                ('totalcompra', models.FloatField()),
                ('estado', models.BooleanField(default=True)),
                ('Administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.administrador')),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
                ('Proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.proveedor')),
            ],
            options={
                'db_table': 'compra',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAdministrador', models.IntegerField()),
                ('fechaVenta', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Venta')),
                ('totalVenta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Venta')),
                ('idCliente', models.ForeignKey(db_column='idCliente', on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
                ('idProducto', models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
            ],
            options={
                'verbose_name': 'venta',
                'verbose_name_plural': 'ventas',
                'db_table': 'venta',
            },
        ),
>>>>>>> sebastian
    ]
